import { CalendarDays, Check, CheckCircle2, CircleDot, Clock3, LayoutGrid, Link2, Route, Sparkles, Target } from 'lucide-react'
import type { Fact, PatientProfile } from '../../shared/types.js'
import { api } from '../api'
import { widgetLabel, widgetTint } from '../widgets'

type View = 'tasks' | 'timeline' | 'plan'

export function CareViews({ view, profile, onChanged, onOpen }: { view: View; profile: PatientProfile; onChanged: () => Promise<void>; onOpen: (id:string)=>void }) {
  if (view === 'tasks') return <Tasks facts={profile.facts} onChanged={onChanged} onOpen={onOpen}/>
  if (view === 'timeline') return <Timeline facts={profile.facts} onOpen={onOpen}/>
  return <Plan facts={profile.facts} onOpen={onOpen}/>
}

const active = (facts:Fact[]) => facts.filter(f=>f.status!=='corrected'&&f.status!=='superseded')

function PageHeading({kicker,title,accent,description,icon}:{kicker:string;title:string;accent:string;description:string;icon:React.ReactNode}) {
  return <div className="care-page-heading"><span className="care-page-icon">{icon}</span><div><p className="eyebrow text-teal">{kicker}</p><h1>{title}<br/><em>{accent}</em></h1><p>{description}</p></div></div>
}

function Tasks({facts,onChanged,onOpen}:{facts:Fact[];onChanged:()=>Promise<void>;onOpen:(id:string)=>void}) {
  const rows=active(facts); const mine=rows.filter(f=>['next_step','readiness','transport'].includes(f.widget)&&f.status!=='completed'); const waiting=rows.filter(f=>['open_loop','referral'].includes(f.widget)&&f.status!=='completed'); const done=rows.filter(f=>f.status==='completed')
  const complete=async(fact:Fact)=>{await api.updateFact(fact.id,{status:'completed'});await onChanged()}
  return <main className="care-page rise"><PageHeading kicker="Tasks & open loops" title="What needs" accent="moving forward?" description="Keep your next actions separate from the things another person or office needs to resolve." icon={<CheckCircle2/>}/><div className="task-columns"><TaskSection title="Your next steps" subtitle="Actions you can move forward" facts={mine} empty="No next steps captured yet." onComplete={complete} onOpen={onOpen}/><TaskSection title="Waiting on" subtitle="Other people and care offices" facts={waiting} empty="Nothing is waiting on someone else." onComplete={complete} onOpen={onOpen}/></div>{done.length>0&&<section className="surface mt-5 rounded-[26px] p-5"><p className="eyebrow">Recently completed</p><div className="mt-3 flex flex-wrap gap-2">{done.slice(0,8).map(f=><button onClick={()=>onOpen(f.conversation_id)} key={f.id} className="rounded-full bg-teal-soft px-3 py-1.5 text-xs text-teal">✓ {f.title}</button>)}</div></section>}</main>
}
function TaskSection({title,subtitle,facts,empty,onComplete,onOpen}:{title:string;subtitle:string;facts:Fact[];empty:string;onComplete:(f:Fact)=>Promise<void>;onOpen:(id:string)=>void}) {return <section className="surface rounded-[28px] p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">{title}</h2><p className="text-xs text-muted">{subtitle}</p></div><span className="rounded-full bg-paper px-2.5 py-1 text-xs font-semibold">{facts.length}</span></div><div className="mt-5 space-y-2">{facts.length?facts.map(f=><article key={f.id} className="task-item"><button onClick={()=>void onComplete(f)} title="Mark done" className="task-check"><Check size={14}/></button><div className="min-w-0 flex-1"><strong>{f.title}</strong><p>{f.detail}</p><button onClick={()=>onOpen(f.conversation_id)} className="text-[10px] font-semibold uppercase tracking-wide text-teal hover:underline">View source conversation</button></div></article>):<div className="empty-inline"><CircleDot size={18}/><span>{empty}</span></div>}</div></section>}

function Timeline({facts,onOpen}:{facts:Fact[];onOpen:(id:string)=>void}) { const rows=active(facts).filter(f=>f.widget==='timeline'||f.widget==='appointment'||f.event_date).sort((a,b)=>String(b.event_date||b.created_at).localeCompare(String(a.event_date||a.created_at))); return <main className="care-page rise"><PageHeading kicker="Care timeline" title="Your care story," accent="in order." description="Important events, appointments, and changes collected across conversations—with the original source kept close." icon={<CalendarDays/>}/><section className="surface rounded-[30px] p-6 sm:p-8">{rows.length?<div className="timeline-list">{rows.map((f,i)=><article key={f.id} className="timeline-entry"><span className={`timeline-node ${i===0?'current':''}`}/><div><time>{f.event_date?new Date(`${f.event_date}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):`Captured ${new Date(f.created_at).toLocaleDateString()}`}</time><h2>{f.title}</h2><p>{f.detail}</p><div className="mt-2 flex items-center gap-2"><span className={`inline-flex rounded-full px-2 py-1 text-[10px] font-semibold ${widgetTint(f.widget)}`}>{widgetLabel(f.widget)}</span><button onClick={()=>onOpen(f.conversation_id)} className="text-[10px] font-semibold text-teal hover:underline">View source</button></div></div></article>)}</div>:<BigEmpty icon={<Clock3/>} title="Your timeline will take shape here" text="Mention an appointment, a past event, or when something changed. Harbor will place it in your story."/>}</section></main> }

function Plan({facts,onOpen}:{facts:Fact[];onOpen:(id:string)=>void}) {const rows=active(facts); const goals=rows.filter(f=>f.widget==='goal'); const prep=rows.filter(f=>['question','readiness','medication'].includes(f.widget)); const people=rows.filter(f=>['person','provider','referral'].includes(f.widget)); return <main className="care-page rise"><PageHeading kicker="Plan & tools" title="Prepare, organize," accent="and follow through." description="Planning views built from the details already in your care thread. Nothing here contacts an office or books care for you." icon={<LayoutGrid/>}/><div className="plan-grid"><PlanCard icon={<Target/>} title="Goals" subtitle="What you are trying to make happen" facts={goals} onOpen={onOpen}/><PlanCard icon={<Sparkles/>} title="Visit preparation" subtitle="Questions, medications, and readiness" facts={prep} onOpen={onOpen}/><PlanCard icon={<Link2/>} title="Care connections" subtitle="People, providers, and referrals" facts={people} onOpen={onOpen}/><section className="plan-card feature"><Route size={22}/><p className="eyebrow mt-5 text-white/60">A connected care journey</p><h2 className="mt-2 text-2xl font-semibold">Every detail has a next use.</h2><p className="mt-2 text-sm leading-relaxed text-white/70">Facts from conversations become preparation, follow-through, and context for the next time you talk.</p></section></div></main>}
function PlanCard({icon,title,subtitle,facts,onOpen}:{icon:React.ReactNode;title:string;subtitle:string;facts:Fact[];onOpen:(id:string)=>void}){return <section className="plan-card"><span className="care-page-icon small">{icon}</span><h2>{title}</h2><p className="subtitle">{subtitle}</p>{facts.length?<ul>{facts.slice(0,5).map(f=><li key={f.id}><span className={`mt-1 h-2 w-2 shrink-0 rounded-full ${f.widget==='question'?'bg-amber':'bg-teal'}`}/><button onClick={()=>onOpen(f.conversation_id)} className="text-left hover:text-teal hover:underline">{f.detail}</button></li>)}</ul>:<p className="empty">This view will fill in as you talk.</p>}</section>}
function BigEmpty({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="big-empty"><span>{icon}</span><h2>{title}</h2><p>{text}</p></div>}
